name: deployed
on:
  status:
    branches:
      - main
jobs:
  test-deployed-page:
    if: github.event.context == 'github/pages' && github.event.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "gh-pages 📑 built successfully ✅"
      - name: show deployed page
        run: curl -s https://glebbahmutov.com/triple-tested
