name: Lint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Lint
      uses: actions/checkout@v2 # Check out the repository first.
      name: prettier
    - uses: actionsx/prettier@v2
        with:
        # prettier CLI arguments.
          args: --check .
